# Generated by Django 3.2.8 on 2022-07-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='dept',
            field=models.CharField(default='소속없음', max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='company',
            field=models.CharField(choices=[('NCS', 'NCS'), ('BRNC', 'BRNC'), ('UNIST', 'UNIST'), ('KINS', 'KINS')], max_length=100),
        ),
    ]
