# Generated by Django 3.2.8 on 2022-07-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0002_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='views',
            field=models.IntegerField(default=0, verbose_name='VIEWS'),
        ),
    ]
