# Generated by Django 3.2.8 on 2022-07-21 06:50

from django.db import migrations, models
import kinsdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0003_docs_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=kinsdb.models.content_file_name)),
                ('serial_num', models.IntegerField(default=0, verbose_name='SERIAL')),
                ('institution', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='docs',
            name='index_num',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='docs',
            name='index_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
