# Generated by Django 3.2.8 on 2022-07-21 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0005_auto_20220721_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kinsdb.document'),
            preserve_default=False,
        ),
    ]
