# Generated by Django 3.2.8 on 2022-07-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0006_docs_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='serial_num',
            field=models.CharField(max_length=100),
        ),
    ]
