# Generated by Django 3.2.8 on 2022-08-02 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kinsdb', '0007_alter_document_serial_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('factor', models.CharField(max_length=100)),
                ('preference', models.TextField()),
                ('description', models.TextField()),
                ('regist_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField()),
                ('keywords', models.ManyToManyField(related_name='keywords', to='kinsdb.Keyword')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
