# Generated by Django 3.2.8 on 2022-08-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0009_site_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='preference',
            field=models.TextField(null=True),
        ),
    ]
