# Generated by Django 3.2.8 on 2022-08-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0010_auto_20220802_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='preference',
            field=models.TextField(blank=True),
        ),
    ]
