# Generated by Django 3.2.8 on 2022-08-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0011_auto_20220802_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='views',
            field=models.IntegerField(default=0, verbose_name='VIEWS'),
        ),
    ]
