# Generated by Django 3.2.8 on 2022-09-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0013_alter_keyword_key_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('requirement', models.TextField(blank=True)),
                ('preference', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='description',
        ),
        migrations.RemoveField(
            model_name='site',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='site',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='site',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='site',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='site',
            name='regist_date',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site',
        ),
        migrations.RemoveField(
            model_name='site',
            name='views',
        ),
        migrations.RemoveField(
            model_name='site',
            name='writer',
        ),
    ]
