# Generated by Django 3.2.8 on 2022-09-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0014_auto_20220905_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='swfactor',
            name='factor',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
