# Generated by Django 3.2.8 on 2022-11-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0015_swfactor_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='keyword',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docs',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='regist_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='docs',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='kinsdb.Tag'),
        ),
    ]
