# Generated by Django 3.2.8 on 2023-01-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0017_auto_20221130_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='sector',
            field=models.CharField(default='-', max_length=40),
        ),
    ]
