# Generated by Django 3.2.8 on 2023-01-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0019_remove_docs_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field',
        ),
    ]
