# Generated by Django 3.2.8 on 2023-03-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0021_auto_20230222_0628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'BRNC_Documents', 'verbose_name_plural': 'BRNC_Documents'},
        ),
    ]
