# Generated by Django 3.2.8 on 2023-03-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0024_report_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='summary',
            new_name='background',
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(null=True, upload_to='kinsdb'),
        ),
    ]
