# Generated by Django 3.2.8 on 2023-03-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0025_auto_20230306_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kinsdb'),
        ),
    ]
