# Generated by Django 3.2.8 on 2023-03-06 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0027_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kinsdb.report'),
            preserve_default=False,
        ),
    ]
