# Generated by Django 3.2.8 on 2023-07-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0030_auto_20230308_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('constitution', models.CharField(max_length=100)),
                ('index_no', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Test',
            },
        ),
    ]
