# Generated by Django 3.2.8 on 2023-07-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0031_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
