# Generated by Django 3.2.8 on 2023-07-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0032_alter_test_content'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(fields=('no', 'index_no'), name='unique doc'),
        ),
    ]
