# Generated by Django 3.2.8 on 2023-08-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0034_docs_unique document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
