# Generated by Django 3.2.8 on 2023-08-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0035_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='index_num',
            field=models.CharField(max_length=100),
        ),
    ]
