# Generated by Django 3.2.8 on 2023-08-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0036_alter_docs_index_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='data/%Y/%m/%d')),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
