# Generated by Django 3.2.8 on 2023-08-02 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0037_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kinsdb.document'),
            preserve_default=False,
        ),
    ]
