# Generated by Django 3.2.8 on 2023-08-02 08:24

from django.db import migrations, models
import kinsdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0038_data_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='file',
            field=models.FileField(upload_to=kinsdb.models.data_file_name),
        ),
    ]
