# Generated by Django 3.2.8 on 2023-08-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0040_docs_wc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='wc',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
