# Generated by Django 3.2.8 on 2023-08-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0041_alter_docs_wc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='wc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
