# Generated by Django 3.2.8 on 2023-08-14 02:11

from django.db import migrations, models
import kinsdb.models


class Migration(migrations.Migration):

    dependencies = [
        ('kinsdb', '0042_alter_docs_wc'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='csv',
            field=models.FileField(blank=True, upload_to=kinsdb.models.csv_file_name),
        ),
    ]
