# Generated by Django 3.2.8 on 2023-01-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_alter_event_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('age', models.IntegerField(default=0)),
                ('grade', models.FloatField(max_length=50, null=True)),
            ],
        ),
    ]
