# Generated by Django 3.2.8 on 2023-10-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0004_files_log_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'Files', 'verbose_name_plural': 'Files'},
        ),
    ]
