# Generated by Django 3.2.8 on 2023-10-05 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_alter_files_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='files',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cloud.files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cloud.post'),
            preserve_default=False,
        ),
    ]
