# Generated by Django 3.2.8 on 2023-10-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_alter_log_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='files',
        ),
        migrations.AddField(
            model_name='files',
            name='log',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cloud.log'),
            preserve_default=False,
        ),
    ]
