# Generated by Django 3.2.8 on 2023-10-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0012_post_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sector',
            field=models.CharField(choices=[('기관 제출 공문', '1'), ('참여기관 공유', '2'), ('회의일정 및 전체자료', '3'), ('기타', '4')], default='기타', max_length=100),
        ),
    ]
