# Generated by Django 3.2.8 on 2023-10-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0014_alter_post_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
