# Generated by Django 3.2.8 on 2023-10-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0015_post_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
