# Generated by Django 3.2.8 on 2023-10-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0017_remove_post_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
