# Generated by Django 3.2.8 on 2023-12-11 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0018_alter_log_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cloud.log'),
        ),
    ]
