# Generated by Django 3.2.8 on 2024-01-25 14:12

import cloud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0019_alter_files_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to=cloud.models.log_file_name),
        ),
    ]
