name: CICD

on:
  push:
    branches: [ "main" ]
	pull_request:
		branches: [ "main" ] 

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |        
            cd /home/devncnc/project/jobcy && git pull https://${{ secrets.ACCESS_TOKEN }}@github.com/ylrang/KINS.git main && ./.scripts/deploy.sh