name: CICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run django test
        run:
          python manage.py test
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Deployment started ..."
            
            # Pull the latest version of the app
            echo "Copying New changes...."         
            cd /home/devncnc/project/jobcy && git pull https://${{ secrets.ACCESS_TOKEN }}@github.com/ylrang/KINS.git main
            echo "New changes copied to server !"
            
            ./.scripts/deploy.sh
